# Generated by Django 3.0.6 on 2020-05-05 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Озаглавие')),
                ('path_to_txt', models.FilePathField(match='.txt$', path='D:\\Рабочий Стол\\Stock_of_articles\\main\\Article_txt', verbose_name='Путь к txt шаблона')),
                ('img', models.ImageField(upload_to='', verbose_name='Картинка на привью')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('views', models.IntegerField(blank=True, editable=False, null=True)),
                ('template_path', models.FilePathField(match='.html$', path='D:\\Рабочий Стол\\Stock_of_articles\\main\\templates\\main', verbose_name='Путь к шаблону')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.Article', verbose_name='Запись')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайкнувший')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='subjects',
            field=models.ManyToManyField(related_name='articles', to='main.Subject', verbose_name='Тематики'),
        ),
    ]
