# Generated by Django 3.0.6 on 2020-05-14 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200513_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subjects',
        ),
        migrations.AddField(
            model_name='article',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='main.Subject', verbose_name='Тематики'),
        ),
    ]
