# Generated by Django 3.0.6 on 2020-05-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200514_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='path_to_txt',
            field=models.FilePathField(match='.txt$', path='/run/media/roman/E (other)/Stock_of_articles/Stock-of-article/main/Article_txt', verbose_name='Путь к txt шаблона'),
        ),
        migrations.AlterField(
            model_name='article',
            name='template_path',
            field=models.FilePathField(match='.html$', path='/run/media/roman/E (other)/Stock_of_articles/Stock-of-article/main/templates/main', verbose_name='Путь к шаблону'),
        ),
    ]
