# Generated by Django 3.0.6 on 2020-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200514_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='color',
            field=models.CharField(blank=True, choices=[('b', 'чернай'), ('w', 'белый')], max_length=1, null=True),
        ),
    ]
