# Generated by Django 3.0.6 on 2020-06-02 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200602_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='published',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Опубликовано'),
        ),
    ]
