# Generated by Django 3.0.6 on 2020-05-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('User', '0002_auto_20200509_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='main.Subject'),
        ),
    ]
