# Generated by Django 3.0.6 on 2020-05-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200506_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activate',
        ),
    ]
