# Generated by Django 3.0.6 on 2020-05-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_delete_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('key', models.IntegerField(unique=True)),
                ('activate', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Активация',
                'verbose_name_plural': 'Активации',
            },
        ),
    ]
