# Generated by Django 3.0.6 on 2020-05-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_activate_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='activate',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Опубликовано'),
        ),
    ]
