# Generated by Django 3.0.6 on 2020-05-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_activate_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activate',
        ),
    ]
