# Generated by Django 3.0.6 on 2020-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200514_1548'),
        ('User', '0007_auto_20200516_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(to='main.Subject'),
        ),
    ]
