# Generated by Django 3.0.6 on 2020-05-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_activate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activate',
        ),
    ]
