# Generated by Django 3.0.6 on 2020-05-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_delete_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
